version: '3.8'

services:
  server:
    build: .
    image: 'urban:latest'
    container_name: urban
    restart: "unless-stopped"
    platform: 'linux/amd64'
    networks:
      - 'default'
    depends_on:
      - 'db'
      - 'redis'
    expose:
      - 8000
  reverse-proxy:
    image: 'nginx:latest'
    container_name: 'nginx_reverse_proxy'
    restart: 'unless-stopped'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - 'data:/var/lib/ssl'
  db:
    image: 'postgres'
    container_name: 'database'
    environment:
      POSTGRES_DB: 'urban'
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_USER: 'urban'
    restart: 'unless-stopped'
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    restart: 'unless-stopped'
    ports:
      - '6379:6379'

volumes:
  data: