version: '3.8'

services:
  server:
    build: .
    image: 'urbn:latest'
    container_name: urbn
    restart: "unless-stopped"
    platform: 'linux/amd64'
    networks:
      - 'default'
    depends_on:
      - 'db'
      - 'redis'
    env_file:
      - .env
    expose:
      - 8000
  reverse-proxy:
    image: 'nginx:latest'
    container_name: 'nginx_reverse_proxy'
    restart: 'unless-stopped'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './data/nginx/:/etc/nginx/conf.d/:ro'
      - './data/certbot/www:/var/www/certbot/:ro'
      - './data/certbot/conf/:/etc/nginx/ssl/:ro'
  certbot:
    image: certbot/certbot:latest
    volumes:
      - './data/certbot/www/:/var/www/certbot/:rw'
      - './data/certbot/conf/:/etc/letsencrypt/:rw'
  db:
    image: 'postgres'
    container_name: 'database'
    environment:
      POSTGRES_DB: 'urbn'
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_USER: 'urbn'
    restart: 'unless-stopped'
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    restart: 'unless-stopped'
    ports:
      - '6379:${REDIS_PORT}'

volumes:
  data: