version: '3.8'

services:
  server:
    build: .
    image: '234408821758.dkr.ecr.af-south-1.amazonaws.com/shoutout:testV3'
    platform: 'linux/amd64'
    networks:
      - 'default'
    depends_on:
      - 'db'
    ports:
      - '80:8000'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '12345'
      POSTGRES_USER: 'shoutout'
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  data: